name: Build
on:
  push:
    branches:
      - kinetic-devel
      - melodic-devel
      - noetic-devel
      - actions
jobs:
  build:
    strategy:
      matrix:
        include:
          - event-ref: refs/heads/kinetic-devel
            rosdistro: kinetic
          - event-ref: refs/heads/actions
            rosdistro: noetic
    if: ${{ github.event.ref == matrix.evnet-ref }}
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.rosdistro }}-ros-base
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          echo ${{ github.event.ref }}