name: Build
on:
  push:
    branches:
      - kinetic-devel
      - melodic-devel
      - noetic-devel
      - actions
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:kinetic-ros-base
    defaults:
      run:
        shell: bash
    steps:
      - uses: yoshito-n-students/usb_cam_hardware/.github/workflows/steps/build@actions
        with:
          rosdistro: kinetic
          branch: kinetic-devel