name: Build
on:
  push:
    branches:
      - kinetic-devel
      - melodic-devel
      - noetic-devel
      - actions
jobs:
  build:
    strategy:
      matrix:
        include:
          - branch: kinetic-devel
            rosdistro: kinetic
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.rosdistro }}-ros-base
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          echo ${{ github.event_path }}